### ISSUE TITLE
2023-03-19 does not have db attached

### ISSUE THREAD

**Issue by konstin** [sethmlarson/pypi-seismometer#22]
seems like the actual db got lost in the [2023-03-19](https://github.com/sethmlarson/pypi-data/releases/tag/2023.03.19) release:

![image](https://user-images.githubusercontent.com/6826232/226633479-81a43dde-e8b0-4e3a-82ec-ac2c9640d7e8.png)

**Comment by sethmlarson** [comment]
Oh no! I see what happened, the database is over the 150MB limit of GitHub even when compressed. That's unfortunate :/

**Comment by konstin** [comment]
maybe a different compression such as zstd could push it down below 150MB again

**Comment by jefftriplett** [comment]
I was here to note the same thing. This might motivate me to add proper django packages integration instead of pulling your data file once a month 😄

**Comment by hugovk** [comment]
Where does the 150 MB limit come from?

https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas says:

> Each file included in a release must be under 2 GB. There is no limit on the total size of a release, nor bandwidth usage.

Is this a different thing?

**Comment by sethmlarson** [comment]
![Screenshot from 2023-03-28 09-49-29](https://user-images.githubusercontent.com/18519037/228277870-d336a9a3-87e9-493d-a161-c81dc56dc091.png)

This is the error I'm seeing when trying to upload the file, the error message is not helpful so I'm not really certain that it's a file size issue. Could be anything, really?

**Comment by sethmlarson** [comment]
Hmm, I'm doubtful it's the file size now, looking in Firefox inspection the request is failing with a CORS error? Very strange :/

**Comment by sethmlarson** [comment]
Welp, the exact same action just succeeded in Chrome, I was using Firefox the whole time trying to upload the file. So maybe this is a web compatibility issue... :fearful: Either way, the `pypi.db.gz` is now available for the release! :rocket:

https://github.com/sethmlarson/pypi-data/releases/tag/2023.03.19
