### ISSUE TITLE
Grab Project description

### ISSUE THREAD

**Issue by anderscui** [sethmlarson/pypi-seismometer#23]
Can you please grab the project description field? I think it's very useful for further mining on pypi database:)

**Comment by sethmlarson** [comment]
Hmm, when you say project description do you mean the short tagline description or the long description? I'm hesitant to add text since I'm already running into issues with the database being too large.

**Comment by anderscui** [comment]
@sethmlarson I mean the long description, but the short tagline description is also useful. Since the openai api is available, we can use the description info to do something interesting :)

**Comment by sethmlarson** [comment]
I'm going to decline this feature request since it'll make the database way larger and I'm more interested in stats/links, sorry about that.
