### ISSUE TITLE
Add a "classifiers" table

### ISSUE THREAD

**Issue by edgarrmondragon** [sethmlarson/pypi-seismometer#28]
For example, it might look something like

| package_name   | name |
|----------|--------|
| requests | Development Status :: 5 - Production/Stable |
| requests | Environment :: Web Environment |
| requests | Intended Audience :: Developers |
| requests | License :: OSI Approved :: Apache Software License |
| requests | Natural Language :: English |

I don't see any intention of normalizing the db, so I think this would be the desired approach.

The `classifiers` array seems to be generally available in `$.info.classifiers` as part of PyPI's JSON API: https://pypi.org/pypi/requests/json

I can submit a PR if this something you consider valuable.

**Comment by sethmlarson** [comment]
I welcome a pull request adding this feature! Thanks for offering :)

**Comment by edgarrmondragon** [comment]
> I welcome a pull request adding this feature! Thanks for offering :)

Done in #29
