### ISSUE TITLE
Grab more wheel metadata

### ISSUE THREAD

**Issue by sethmlarson** [sethmlarson/pypi-seismometer#4]
Check .dist-info and see what can be grabbed.

**Comment by ofek** [comment]
I'm quite interested in the `Generator` in `WHEEL` files so I can see who's using Hatchling and (less important) with what versions!

**Comment by sethmlarson** [comment]
@ofek Thanks for your interest in this project! If you've got time to contribute scraping wheel metadata I'd happily review the PR run the job and publish the results.

**Comment by ofek** [comment]
Done! https://github.com/sethmlarson/pypi-data/pull/8
